### ISSUE TITLE
APIv2: encoding/prototext: crash in parsing invalid map message values

### ISSUE THREAD

**Issue by neild** [golang/protobuf#1003]
Minimal fuzzer test case:

```
test_all_types{map_string_nested_message{value:A}}
```

```
panic: value is not a message [recovered]
	panic: value is not a message

goroutine 20 [running]:
testing.tRunner.func1(0xc0000e18c0)
	/Users/dneil/src/go/src/testing/testing.go:916 +0x608
panic(0x12389e0, 0x12ebe50)
	/Users/dneil/src/go/src/runtime/panic.go:967 +0x15d
google.golang.org/protobuf/internal/encoding/text.Value.Message(...)
	/Users/dneil/protobuf.new/internal/encoding/text/value.go:318
google.golang.org/protobuf/encoding/prototext.UnmarshalOptions.unmarshalMapMessageValue(0x1, 0x12f5340, 0xc000092330, 0x7, 0xc00028202f, 0x1, 0x1, 0x149cf01, 0x1, 0x0, ...)
	/Users/dneil/protobuf.new/encoding/prototext/decode.go:426 +0x25e
google.golang.org/protobuf/encoding/prototext.UnmarshalOptions.unmarshalMap(0x1270001, 0x12f5340, 0xc000092330, 0xc000174ac0, 0x1, 0x1, 0x12fa4a0, 0xc0001cf3a0, 0x12f7260, 0xc000290000, ...)
	/Users/dneil/protobuf.new/encoding/prototext/decode.go:366 +0x553
google.golang.org/protobuf/encoding/prototext.UnmarshalOptions.unmarshalMessage(0x1280001, 0x12f5340, 0xc000092330, 0xc00020c270, 0x1, 0x1, 0x12f9a60, 0xc00028c000, 0x1, 0x0)
	/Users/dneil/protobuf.new/encoding/prototext/decode.go:191 +0x963
google.golang.org/protobuf/encoding/prototext.UnmarshalOptions.unmarshalSingular(0xc0000a0001, 0x12f5340, 0xc000092330, 0x9, 0xc00028200e, 0x24, 0x24, 0x0, 0x0, 0x0, ...)
	/Users/dneil/protobuf.new/encoding/prototext/decode.go:237 +0x31d
google.golang.org/protobuf/encoding/prototext.UnmarshalOptions.unmarshalMessage(0xc000280001, 0x12f5340, 0xc000092330, 0xc00020c340, 0x1, 0x1, 0x12f9a60, 0xc000284000, 0x0, 0x0)
	/Users/dneil/protobuf.new/encoding/prototext/decode.go:209 +0xb17
google.golang.org/protobuf/encoding/prototext.UnmarshalOptions.Unmarshal(0x1280001, 0x12f5340, 0xc000092330, 0xc000282000, 0x32, 0x232, 0x12f1a80, 0xc000284000, 0xc000282000, 0x32)
	/Users/dneil/protobuf.new/encoding/prototext/decode.go:67 +0x1e6
```

**Comment by cybrcodr** [comment]
Just checked.  https://golang.org/cl/204602 fixes this and simply returns error.  I'll mark this fixed once that CL is checked in.
