### ISSUE TITLE
panic when marshal pb message which has oneof field

### ISSUE THREAD

**Issue by songtianyi** [golang/protobuf#1005]
**What version of protobuf and what language are you using?**
```
libprotoc 3.3.0
go version go1.13 darwin/amd64
```

**What did you do?**
```
package main

import (
	"fmt"
	"github.com/gogo/protobuf/proto"
	"github.com/sky-cloud-tec/proto/v1/eventti"
)

func main() {
	foo := &eventti.EmailServerCfg{
		Account:  "test@test.net",
		Password: "tes",
		Host:     "localhost",
		Port:     554,
		Protocol: eventti.EmailProtocol_SMTP,
	}

	req := &eventti.CreateNotificationChannelReq{
		Name:   "test",
		Etypes: []eventti.EventType{eventti.EventType_DEVICE_CONFIG_UPDATED},
		Type:   eventti.NotificationChannelType_EMAIL,
		Cfg:    &eventti.CreateNotificationChannelReq_EmailServerCfg{EmailServerCfg: foo},
		Target: nil,
	}

	fmt.Println(req.String())

	proto.Marshal(req)

}

```

**What did you expect to see?**
exit properly
**What did you see instead?**
```
name:"test" etypes:DEVICE_CONFIG_UPDATED type:EMAIL email_server_cfg:<account:"songtianyi@sky-cloud.net" password:"tes" host:"localhost" port:554 protocol:SMTP >
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x11134a9]

goroutine 1 [running]:
github.com/gogo/protobuf/proto.makeOneOfMarshaler.func1(0xc00004c108, 0x0, 0x3)
	/Users/work/go/pkg/mod/github.com/gogo/protobuf@v1.3.1/proto/table_marshal.go:2598 +0x129
github.com/gogo/protobuf/proto.(*marshalInfo).size(0xc0000c2000, 0xc00004c0c0, 0xc00000c0e0)
	/Users/work/go/pkg/mod/github.com/gogo/protobuf@v1.3.1/proto/table_marshal.go:200 +0x9d
github.com/gogo/protobuf/proto.(*InternalMessageInfo).Size(0xc00000c0e0, 0x120d2c0, 0xc00004c0c0, 0x0)
	/Users/work/go/pkg/mod/github.com/gogo/protobuf@v1.3.1/proto/table_marshal.go:131 +0x66
github.com/gogo/protobuf/proto.Marshal(0x120d2c0, 0xc00004c0c0, 0xc0000b1f40, 0x1, 0x1, 0xa3, 0x0)
	/Users/work/go/pkg/mod/github.com/gogo/protobuf@v1.3.1/proto/table_marshal.go:2952 +0xfe
main.main()
	/Users/work/trash/create_notification_req.go:28 +0x22e
```
**Anything else we should know about your project / environment?**

**Comment by puellanivis** [comment]
It looks like you’re using `gogo/protobuf` not `golang/protobuf` there is not much we can help you with here.
