### ISSUE TITLE
internal/impl: deadlock when calling proto.RegisterExtension

### ISSUE THREAD

**Issue by johanbrandhorst** [golang/protobuf#1052]
**What version of protobuf and what language are you using?**
Version: `v1.4.0-rc.3`

**What did you do?**
Tried running https://play.golang.org/p/_dSwb-FLKzk locally.

**What did you expect to see?**
The program finishing successfully

**What did you see instead?**
A mutex deadlock trace:

```
$ go run main.go 
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [semacquire, locked to thread]:
sync.runtime_SemacquireMutex(0x868fec, 0xc00008d700, 0x0)
        /usr/lib/go/src/runtime/sema.go:71 +0x47
sync.(*RWMutex).RLock(...)
        /usr/lib/go/src/sync/rwmutex.go:50
google.golang.org/protobuf/reflect/protoregistry.(*Files).FindDescriptorByName(0xc000104340, 0xc000177405, 0x1c, 0x0, 0x0, 0x0, 0x0)
        /go/pkg/mod/google.golang.org/protobuf@v1.20.0/reflect/protoregistry/registry.go:157 +0xa08
google.golang.org/protobuf/internal/impl.resolverOnly.FindDescriptorByName(0xc000104340, 0xc000177405, 0x1c, 0x0, 0x0, 0x0, 0xc000177321)
        /go/pkg/mod/google.golang.org/protobuf@v1.20.0/internal/impl/legacy_file.go:77 +0x3f
google.golang.org/protobuf/internal/filedesc.(*File).resolveMessageDependency(0xc00013ea80, 0x6a7480, 0xc0001047e0, 0x1, 0x52e0d1, 0xc0001967a1)
        /go/pkg/mod/google.golang.org/protobuf@v1.20.0/internal/filedesc/desc_lazy.go:125 +0x18a
google.golang.org/protobuf/internal/filedesc.newRawFile(0x0, 0x0, 0xc000196600, 0x1a8, 0x200, 0x1, 0x1, 0x6a1680, 0xc0001062d0, 0x6a3300, ...)
        /go/pkg/mod/google.golang.org/protobuf@v1.20.0/internal/filedesc/desc_init.go:35 +0x2a9
google.golang.org/protobuf/internal/filedesc.Builder.Build(0x0, 0x0, 0xc000196600, 0x1a8, 0x200, 0x1, 0x1, 0x6a1680, 0xc0001062d0, 0x6a3300, ...)
        /go/pkg/mod/google.golang.org/protobuf@v1.20.0/internal/filedesc/build.go:103 +0xb0
google.golang.org/protobuf/internal/impl.legacyLoadFileDesc(0x8253e0, 0x12f, 0x12f, 0x12f, 0xc0001262a0)
        /go/pkg/mod/google.golang.org/protobuf@v1.20.0/internal/impl/legacy_file.go:62 +0x227
google.golang.org/protobuf/internal/impl.LegacyLoadEnumDesc(0x6a7d40, 0x615fc0, 0xc000126298, 0x7f3c41aef328)
        /go/pkg/mod/google.golang.org/protobuf@v1.20.0/internal/impl/legacy_enum.go:137 +0x3a9
google.golang.org/protobuf/internal/impl.(*ExtensionInfo).initFromLegacy(0x83a220)
        /go/pkg/mod/google.golang.org/protobuf@v1.20.0/internal/impl/legacy_extension.go:100 +0x715
google.golang.org/protobuf/internal/impl.(*ExtensionInfo).lazyInitSlow(0x83a220)
        /go/pkg/mod/google.golang.org/protobuf@v1.20.0/internal/impl/extension.go:134 +0x26e
google.golang.org/protobuf/internal/impl.(*ExtensionInfo).TypeDescriptor(0x83a220, 0xc000106c30, 0xc00008de68)
        /go/pkg/mod/google.golang.org/protobuf@v1.20.0/internal/impl/extension.go:112 +0x51
google.golang.org/protobuf/reflect/protoregistry.(*Types).RegisterExtension(0xc0001062d0, 0x6a5ec0, 0x83a220, 0x0, 0x0)
        /go/pkg/mod/google.golang.org/protobuf@v1.20.0/reflect/protoregistry/registry.go:454 +0x81
github.com/golang/protobuf/proto.RegisterExtension(...)
        /go/pkg/mod/github.com/golang/protobuf@v1.4.0-rc.3/proto/registry.go:285
google.golang.org/genproto/googleapis/api/annotations.init.4()
        /go/pkg/mod/google.golang.org/genproto@v0.0.0-20200305110556-506484158171/googleapis/api/annotations/field_behavior.pb.go:96 +0x7a
exit status 2
```
This line seems to be causing it:
```
proto.RegisterExtension(E_FieldBehavior)
```

Ref: https://github.com/googleapis/go-genproto/blob/master/googleapis/api/annotations/field_behavior.pb.go#L96

**Anything else we should know about your project / environment?**
This is causing the grpc-gateway project generators to lock up at generation time. It is _not_ causing this simple deadlock panic, it seems to be blocking somehow. I'm still investigating, see https://github.com/grpc-ecosystem/grpc-gateway/issues/1158.

**Comment by dsnet** [comment]
Thanks for the bug report. Without looking into it deeply, it seems like a reentrant deadlock issue where the legacy wrapper code is calling itself with the legacy lock already held.

**Comment by neild** [comment]
The problem is that creating the ExtensionDescriptor for a legacy ExtensionDesc  can call into the global registry to resolve types.

Either we need to add another layer of lazy initialization to legacy ExtensionDescs or we can revive https://go-review.googlesource.com/c/protobuf/+/204804 to trigger lazy init outside the registry lock being held. I think I'd rather do the latter, because it'll take a fair bit of additional complexity to add even more layers of lazy init.

**Comment by neild** [comment]
Thanks for the bug report! Until we tag a release with the fix (probably Monday), you can work around the problem by depending on `google.golang.org/protobuf` `v1.20.1-0.20200305173516-13e7f145cc57`.
