### ISSUE TITLE
JSONpb marshal

### ISSUE THREAD

**Issue by Dasio** [golang/protobuf#1096]
**What version of protobuf and what language are you using?**
Version: 1.4.0

**What did you do?**
Upgraded 	github.com/golang/protobuf v1.3.5 to 1.4.0

**What did you see instead?**
Panic:
```
2020/04/21 11:59:41 http: panic serving [::1]:43996: reflect: call of reflect.Value.IsNil on struct Value
goroutine 75 [running]:
net/http.(*conn).serve.func1(0xc00014b9a0)
	/usr/lib/go/src/net/http/server.go:1772 +0x139
panic(0xfac740, 0xc0000c7060)
	/usr/lib/go/src/runtime/panic.go:975 +0x3e3
reflect.Value.IsNil(...)
	/usr/lib/go/src/reflect/value.go:1063
google.golang.org/protobuf/internal/impl.fieldInfoForMessage.func1(0xc00034e460, 0x1337320)
	/home/dasio/go/pkg/mod/google.golang.org/protobuf@v1.21.0/internal/impl/message_reflect_field.go:388 +0x13f
google.golang.org/protobuf/internal/impl.(*messageReflectWrapper).Has(0xc000248120, 0x1337320, 0xc00078bd20, 0x110ac20)
	/home/dasio/go/pkg/mod/google.golang.org/protobuf@v1.21.0/internal/impl/message_reflect_gen.go:187 +0x82
github.com/golang/protobuf/jsonpb.(*jsonWriter).marshalMessage(0xc000357340, 0x1333500, 0xc000248120, 0x0, 0x0, 0x0, 0x0, 0x203000, 0x203000)
	/home/dasio/go/pkg/mod/github.com/golang/protobuf@v1.4.0/jsonpb/encode.go:245 +0x8cd
github.com/golang/protobuf/jsonpb.(*Marshaler).marshal(0xc0001a7050, 0x13141c0, 0xc00034e460, 0x28, 0xc0003573c0, 0x40c653, 0x10038c0, 0x112bc20)
	/home/dasio/go/pkg/mod/github.com/golang/protobuf@v1.4.0/jsonpb/encode.go:116 +0x1fe
github.com/golang/protobuf/jsonpb.(*Marshaler).Marshal(0xc0001a7050, 0x12fb500, 0xc0002825d0, 0x13141c0, 0xc00034e460, 0x104fb01, 0xebbd01)
	/home/dasio/go/pkg/mod/github.com/golang/protobuf@v1.4.0/jsonpb/encode.go:67 +0x46
github.com/grpc-ecosystem/grpc-gateway/runtime.(*JSONPb).marshalTo(0xc0001a7050, 0x12fb500, 0xc0002825d0, 0x112bc20, 0xc00034e460, 0xfdf001, 0x112bc20)
	/home/dasio/go/pkg/mod/github.com/grpc-ecosystem/grpc-gateway@v1.14.4/runtime/marshal_jsonpb.go:50 +0x10d
github.com/grpc-ecosystem/grpc-gateway/runtime.(*JSONPb).Marshal(0xc0001a7050, 0x112bc20, 0xc00034e460, 0x0, 0x0, 0xc00034e400, 0x1b5af28, 0x0)
	/home/dasio/go/pkg/mod/github.com/grpc-ecosystem/grpc-gateway@v1.14.4/runtime/marshal_jsonpb.go:34 +0x9d
github.com/grpc-ecosystem/grpc-gateway/runtime.ForwardResponseMessage(0x131ff40, 0xc0002825a0, 0xc0000e4460, 0x1324400, 0xc0001a7050, 0x1319080, 0xc00034e380, 0xc0000f2500, 0x13141c0, 0xc00034e460, ...)
	/home/dasio/go/pkg/mod/github.com/grpc-ecosystem/grpc-gateway@v1.14.4/runtime/handler.go:155 +0x3bc
```
It's because of this model
```go
type User struct {
	Id                          string          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" `
	core.Timestamp              `protobuf:"bytes,30,opt,name=timestamp,proto3,embedded=timestamp" json:""`
}

type Timestamp struct {
	Created int64 `protobuf:"varint,30,opt,name=created,proto3" json:"created,omitempty"`
	Updated int64 `protobuf:"varint,31,opt,name=updated,proto3" json:"updated,omitempty"`
	Deleted int64 `protobuf:"varint,32,opt,name=deleted,proto3" json:"deleted,omitempty"`
}
```
When I remove embedded Timestamp it works. Proto is generated with gogo-slick

When I downgraded to 1.3.5 it works again.
Any idea what is wrong? Maybe some breakign change I need adjust to?

**Comment by neild** [comment]
>  Proto is generated with gogo-slick

The `github.com/golang/protobuf` module only supports generated code produced by `github.com/golang/protobuf/protoc-gen-go` or `google.golang.org/protobuf/cmd/protoc-gen-go`. You should use the gogoprotobuf packages for code produced by its generator.

**Comment by dsnet** [comment]
Interoperability between golang/protobuf and gogo/protobuf has always been flaky.

Closing as directly supporting gogo/protobuf is outside out support domain. You'll need to file an issue with that project for its generator to support implementing the [protobuf reflection interface](https://pkg.go.dev/google.golang.org/protobuf/proto?tab=doc#Message), in which case our runtime will be able to handle those types.
