### ISSUE TITLE
proto: panic when calling `String()` on proto with hand written type declaration

### ISSUE THREAD

**Issue by rohany** [golang/protobuf#1139]
**What version of protobuf and what language are you using?**
Version: `libprotoc 3.10.1`

**What did you do?**
I have a proto message that I suppress the type declaration of, and another message that stores this message. I suppress the type declaration in order to store some extra data with the message that is purely in memory. If `String()` is used on the message that stores the proto with the suppressed type declaration, a panic occurs. Reproduction go and proto files are below:

main.go:
```
package main

import "fmt"

type Extra struct {
	stuff [][]byte
}

type T1 struct {
	Contents T2
	ExtraStuff Extra
}

func main() {
  x := T1 {
	  ExtraStuff: Extra{stuff: [][]byte{[]byte{0}, []byte{0}}},
	  Contents: T2{},
  }
  y := T1 {
	  ExtraStuff: Extra{},
	  Contents: T2{Contents: &x},
  }
  fmt.Println(y.String())
}
```

test.proto:
```
syntax = "proto2";
option go_package = "main";
import "gogoproto/gogo.proto";


message T1 {
  option (gogoproto.typedecl) = false;
  optional T2 contents = 1 [(gogoproto.nullable) = false];
}

message T2 {
  optional T1 contents = 1;
}
```

I generate the proto with:

```
protoc protos/*.proto -I=.:../go/src/github.com/cockroachdb/cockroach/vendor/github.com/gogo/protobuf/ --go_out=.
```

and compile the program with:
```
go build main.go test.pb.go
```

Running main.go produces a panic:
```
➜  protos ./main
panic: reflect.Value.Bytes of non-byte slice

goroutine 1 [running]:
reflect.Value.Bytes(0x11902a0, 0xc00000c068, 0x1b7, 0xc000079380, 0xc00013a908, 0x10fd74d)
	/usr/local/Cellar/go/1.14/libexec/src/reflect/value.go:275 +0x11a
github.com/gogo/protobuf/proto.(*TextMarshaler).writeAny(0x1329230, 0xc00000c0a0, 0x11902a0, 0xc00000c068, 0x1b7, 0xc000132300, 0x120eec0, 0x11902a0)
	/Users/rohany/go/src/github.com/gogo/protobuf/proto/text.go:559 +0x64d
github.com/gogo/protobuf/proto.(*TextMarshaler).writeStruct(0x1329230, 0xc00000c0a0, 0x11a8a40, 0xc00000c068, 0x199, 0x199, 0x0)
	/Users/rohany/go/src/github.com/gogo/protobuf/proto/text.go:453 +0x8c8
github.com/gogo/protobuf/proto.(*TextMarshaler).writeAny(0x1329230, 0xc00000c0a0, 0x11a8a40, 0xc00000c068, 0x199, 0xc000132100, 0x120eec0, 0x11a8a40)
	/Users/rohany/go/src/github.com/gogo/protobuf/proto/text.go:606 +0x26f
github.com/gogo/protobuf/proto.(*TextMarshaler).writeStruct(0x1329230, 0xc00000c0a0, 0x11ae3c0, 0xc00000c060, 0x199, 0x199, 0x11a1b80)
	/Users/rohany/go/src/github.com/gogo/protobuf/proto/text.go:453 +0x8c8
github.com/gogo/protobuf/proto.(*TextMarshaler).writeAny(0x1329230, 0xc00000c0a0, 0x11c0440, 0xc00000c080, 0x196, 0xc000132200, 0x120eec0, 0x11c0440)
	/Users/rohany/go/src/github.com/gogo/protobuf/proto/text.go:606 +0x26f
github.com/gogo/protobuf/proto.(*TextMarshaler).writeStruct(0x1329230, 0xc00000c0a0, 0x11a8ac0, 0xc00000c080, 0x199, 0x199, 0x11a1b80)
	/Users/rohany/go/src/github.com/gogo/protobuf/proto/text.go:453 +0x8c8
github.com/gogo/protobuf/proto.(*TextMarshaler).writeAny(0x1329230, 0xc00000c0a0, 0x11a8ac0, 0xc00000c080, 0x199, 0xc000132000, 0x120eec0, 0x11a8ac0)
	/Users/rohany/go/src/github.com/gogo/protobuf/proto/text.go:606 +0x26f
github.com/gogo/protobuf/proto.(*TextMarshaler).writeStruct(0x1329230, 0xc00000c0a0, 0x11ae3c0, 0xc00000c080, 0x199, 0x199, 0x1500108)
	/Users/rohany/go/src/github.com/gogo/protobuf/proto/text.go:453 +0x8c8
github.com/gogo/protobuf/proto.(*TextMarshaler).Marshal(0x1329230, 0x120aae0, 0xc000076780, 0x120d660, 0xc00000c080, 0x11ae3c0, 0xc000104f01)
	/Users/rohany/go/src/github.com/gogo/protobuf/proto/text.go:896 +0x226
github.com/gogo/protobuf/proto.(*TextMarshaler).Text(0x1329230, 0x120d660, 0xc00000c080, 0x98, 0xc000104f78)
	/Users/rohany/go/src/github.com/gogo/protobuf/proto/text.go:908 +0x6e
github.com/gogo/protobuf/proto.CompactTextString(...)
	/Users/rohany/go/src/github.com/gogo/protobuf/proto/text.go:930
main.(*T1).String(...)
	/Users/rohany/protobug/protos/test.pb.go:25
main.main()
	/Users/rohany/protobug/protos/main.go:23 +0x14b
```

Let me know if these is anything else I can do to help!

**Comment by rohany** [comment]
Sorry, I've posted this in the wrong repository.
