### ISSUE TITLE
convert: panic error, use Gogoproto CastType int

### ISSUE THREAD

**Issue by tonyboxes** [golang/protobuf#1237]
Version: v1.4.3

proto:
```
syntax = "proto3";
package helloworld;
import "github.com/gogo/protobuf/gogoproto/gogo.proto";

message Hello {
  string name = 1;
  int64 age = 2 [(gogoproto.casttype) = "int"];
}

// generate
protoc -I=. -I=$GOPATH/src --gofast_out=. *.proto
```
go_test:
```
import (
	"testing"

	proto "github.com/golang/protobuf/proto"
)

func TestProto(t *testing.T) {
	h := &Hello{Name: "hi", Age: 100}
	b, err := proto.Marshal(h)
	if err != nil {
		t.Fatal(err)
	}
	t.Log(b)
}
```
return errors:
```
panic: invalid Go type int:3 for field helloworld.Hello.age [recovered]
	panic: invalid Go type int:3 for field helloworld.Hello.age

goroutine 6 [running]:
testing.tRunner.func1.1(0x12dc4c0, 0xc000048940)
	/usr/local/go/src/testing/testing.go:1057 +0x30d
testing.tRunner.func1(0xc000001380)
	/usr/local/go/src/testing/testing.go:1060 +0x41a
panic(0x12dc4c0, 0xc000048940)
	/usr/local/go/src/runtime/panic.go:969 +0x175
google.golang.org/protobuf/internal/impl.newSingularConverter(0x1399680, 0x12dbd00, 0x1399560, 0xc0001189a0, 0x1397201, 0xc00000c2e0)
	/Users/chenzhihui/Workspace/go/pkg/mod/google.golang.org/protobuf@v1.23.0/internal/impl/convert.go:143 +0xfcd
google.golang.org/protobuf/internal/impl.NewConverter(0x1399680, 0x12dbd00, 0x1399560, 0xc0001189a0, 0x203000, 0xc000011080)
	/Users/chenzhihui/Workspace/go/pkg/mod/google.golang.org/protobuf@v1.23.0/internal/impl/convert.go:60 +0xdc
google.golang.org/protobuf/internal/impl.fieldInfoForScalar(0x1399560, 0xc0001189a0, 0x12e9cd3, 0x3, 0x0, 0x0, 0x1399680, 0x12dbd00, 0x12e9cd8, 0x49, ...)
	/Users/chenzhihui/Workspace/go/pkg/mod/google.golang.org/protobuf@v1.23.0/internal/impl/message_reflect_field.go:234 +0x115
google.golang.org/protobuf/internal/impl.(*MessageInfo).makeKnownFieldsFunc(0xc00011e640, 0x30, 0xffffffffffffffff, 0x18, 0xffffffffffffffff, 0xc000010f60, 0xc000010f90, 0xc000010fc0, 0xc000010ff0)
	/Users/chenzhihui/Workspace/go/pkg/mod/google.golang.org/protobuf@v1.23.0/internal/impl/message_reflect.go:67 +0x97d
google.golang.org/protobuf/internal/impl.(*MessageInfo).makeReflectFuncs(0xc00011e640, 0x1399680, 0x131ba20, 0x30, 0xffffffffffffffff, 0x18, 0xffffffffffffffff, 0xc000010f60, 0xc000010f90, 0xc000010fc0, ...)
	/Users/chenzhihui/Workspace/go/pkg/mod/google.golang.org/protobuf@v1.23.0/internal/impl/message_reflect.go:36 +0x65
google.golang.org/protobuf/internal/impl.(*MessageInfo).initOnce(0xc00011e640)
	/Users/chenzhihui/Workspace/go/pkg/mod/google.golang.org/protobuf@v1.23.0/internal/impl/message.go:90 +0x192
google.golang.org/protobuf/internal/impl.(*MessageInfo).init(...)
	/Users/chenzhihui/Workspace/go/pkg/mod/google.golang.org/protobuf@v1.23.0/internal/impl/message.go:72
google.golang.org/protobuf/internal/impl.(*messageReflectWrapper).ProtoMethods(0xc0000488a0, 0xc000068d78)
	/Users/chenzhihui/Workspace/go/pkg/mod/google.golang.org/protobuf@v1.23.0/internal/impl/message_reflect_gen.go:150 +0x53
google.golang.org/protobuf/proto.protoMethods(...)
	/Users/chenzhihui/Workspace/go/pkg/mod/google.golang.org/protobuf@v1.23.0/proto/proto_methods.go:18
google.golang.org/protobuf/proto.MarshalOptions.marshal(0xc000000001, 0x0, 0x0, 0x0, 0x1398b20, 0xc0000488a0, 0xc0000488a0, 0x1398b20, 0xc0000488a0, 0x1327fc0, ...)
	/Users/chenzhihui/Workspace/go/pkg/mod/google.golang.org/protobuf@v1.23.0/proto/encode.go:140 +0x49
google.golang.org/protobuf/proto.MarshalOptions.MarshalAppend(0x1000001, 0x0, 0x0, 0x0, 0x1391440, 0xc0000488a0, 0x1629108, 0x0, 0x14456b8, 0x1532600, ...)
	/Users/chenzhihui/Workspace/go/pkg/mod/google.golang.org/protobuf@v1.23.0/proto/encode.go:125 +0x98
github.com/golang/protobuf/proto.marshalAppend(0x0, 0x0, 0x0, 0x1395920, 0xc000020840, 0xc00003a700, 0x1068b7b, 0x32a41e70580c8, 0x856a8a8, 0x856a8a80000000f, ...)
	/Users/chenzhihui/Workspace/go/pkg/mod/github.com/golang/protobuf@v1.4.3/proto/wire.go:40 +0xc7
github.com/golang/protobuf/proto.Marshal(...)
	/Users/chenzhihui/Workspace/go/pkg/mod/github.com/golang/protobuf@v1.4.3/proto/wire.go:23
proto-test/api.TestProto(0xc000001380)
	/Users/chenzhihui/Workspace/go/src/proto-test/api/api_test.go:11 +0x89
testing.tRunner(0xc000001380, 0x134d000)
	/usr/local/go/src/testing/testing.go:1108 +0xef
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1159 +0x386
exit status 2
FAIL	proto-test/api	0.557s
```

**Comment by neild** [comment]
Since you're using gogoproto, this should be filed on that project's [issue tracker](https://github.com/gogo/protobuf/issues).

**Comment by dsnet** [comment]
Closing. This module cannot be expected to handle types that are not created by the generator provided by this module. The [protobuf reflection interfaces](https://pkg.go.dev/google.golang.org/protobuf/reflect/protoreflect) provide a way for external implementations of types to cooperate with the protobuf libraries. However, it is the responsibility of custom types to implement such interfaces
