### ISSUE TITLE
fatal error: invalid pointer found on stack

### ISSUE THREAD

**Issue by danielcondemarin** [golang/protobuf#1375]
**What version of protobuf and what language are you using?**
Version: google.golang.org/protobuf v1.27.1
Go version: 1.17.2-alpine3.13

**What did you do?**

Calling `proto.Marshal` results in the following unrecoverable runtime error: `fatal error: invalid pointer found on stack`. Unfortunately I haven't found a way to replicate it myself and can't share all the relevant code as is private. 

**Stacktrace:**

```
2021-10-20T05:10:15.787+01:00
runtime.morestack()
7400
2021-10-20T05:10:15.787+01:00
/usr/local/go/src/runtime/asm_amd64.s:461 +0x8b fp=0x7fc8f7716a40 sp=0x7fc8f7716a38 pc=0x46890b
7401
2021-10-20T05:10:15.787+01:00
goroutine 261258045 [copystack]:
7402
2021-10-20T05:10:15.787+01:00
runtime.deferCallSave(0xc004d51490, 0xc004d51f38)
7403
2021-10-20T05:10:15.787+01:00
/usr/local/go/src/runtime/panic.go:941 +0xca fp=0xc004d51398 sp=0xc004d51390 pc=0x436d8a
7404
2021-10-20T05:10:15.787+01:00
runtime.runOpenDeferFrame(0x80, 0xc0079d09b0)
7405
2021-10-20T05:10:15.787+01:00
/usr/local/go/src/runtime/panic.go:889 +0x27b fp=0xc004d51418 sp=0xc004d51398 pc=0x4366db
7406
2021-10-20T05:10:15.787+01:00
panic({0x1619f80, 0x2d72fd0})
7407
2021-10-20T05:10:15.787+01:00
/usr/local/go/src/runtime/panic.go:1038 +0x215 fp=0xc004d514d8 sp=0xc004d51418 pc=0x436fb5
7408
2021-10-20T05:10:15.787+01:00
runtime.panicmem(...)
7409
2021-10-20T05:10:15.787+01:00
/usr/local/go/src/runtime/panic.go:221
7410
2021-10-20T05:10:15.787+01:00
runtime.sigpanic()
7411
2021-10-20T05:10:15.787+01:00
/usr/local/go/src/runtime/signal_unix.go:735 +0x327 fp=0xc004d51528 sp=0xc004d514d8 pc=0x44d9c7
7412
2021-10-20T05:10:15.787+01:00
google.golang.org/protobuf/internal/impl.pointer.Int64(...)
7413
2021-10-20T05:10:15.787+01:00
/go/src/github.com/x/y/vendor/google.golang.org/protobuf/internal/impl/pointer_unsafe.go:93
7414
2021-10-20T05:10:15.787+01:00
google.golang.org/protobuf/internal/impl.sizeInt64NoZero({0x4157c5}, 0x16a8140, {0x90})
7415
2021-10-20T05:10:15.787+01:00
/go/src/github.com/x/y/vendor/google.golang.org/protobuf/internal/impl/codec_gen.go:1853 fp=0xc004d51530 sp=0xc004d51528 pc=0x7dbd40
7416
2021-10-20T05:10:15.787+01:00
google.golang.org/protobuf/internal/impl.(*MessageInfo).sizePointerSlow(0xc0004189a8, {0xc00476cf00}, {0x90})
7417
2021-10-20T05:10:15.787+01:00
/go/src/github.com/x/y/vendor/google.golang.org/protobuf/internal/impl/encode.go:79 +0xd9 fp=0xc004d51588 sp=0xc004d51530 pc=0x7ff019
7418
2021-10-20T05:10:15.787+01:00
google.golang.org/protobuf/internal/impl.(*MessageInfo).sizePointer(0x5, {0xc006824648}, {0xc3})
7419
2021-10-20T05:10:15.787+01:00
/go/src/github.com/x/y/vendor/google.golang.org/protobuf/internal/impl/encode.go:56 +0x76 fp=0xc004d515c0 sp=0xc004d51588 pc=0x7feef6
7420
2021-10-20T05:10:15.787+01:00
google.golang.org/protobuf/internal/impl.sizeMessageSliceInfo({0xc009fcb330}, 0xc0059862f8, {0x4e})
7421
2021-10-20T05:10:15.787+01:00
/go/src/github.com/x/y/vendor/google.golang.org/protobuf/internal/impl/codec_field.go:473 +0x55 fp=0xc004d51610 sp=0xc004d515c0 pc=0x7d1595
7422
2021-10-20T05:10:15.787+01:00
google.golang.org/protobuf/internal/impl.(*MessageInfo).sizePointerSlow(0xc000417900, {0x0}, {0x38})
7423
2021-10-20T05:10:15.787+01:00
/go/src/github.com/x/y/vendor/google.golang.org/protobuf/internal/impl/encode.go:79 +0xd9 fp=0xc004d51668 sp=0xc004d51610 pc=0x7ff019
7424
2021-10-20T05:10:15.787+01:00
google.golang.org/protobuf/internal/impl.(*MessageInfo).sizePointer(0x26, {0x40eb25}, {0x94})
7425
2021-10-20T05:10:15.787+01:00
/go/src/github.com/x/y/vendor/google.golang.org/protobuf/internal/impl/encode.go:56 +0x76 fp=0xc004d516a0 sp=0xc004d51668 pc=0x7feef6
7426
2021-10-20T05:10:15.787+01:00
google.golang.org/protobuf/internal/impl.sizeMessageSliceInfo({0xc005155560}, 0xc0046fd8c0, {0x0})
7427
2021-10-20T05:10:15.787+01:00
/go/src/github.com/x/y/vendor/google.golang.org/protobuf/internal/impl/codec_field.go:473 +0x55 fp=0xc004d516f0 sp=0xc004d516a0 pc=0x7d1595
7428
2021-10-20T05:10:15.787+01:00
google.golang.org/protobuf/internal/impl.(*MessageInfo).sizePointerSlow(0xc000417b90, {0xc009fcb330}, {0xff})
7429
2021-10-20T05:10:15.787+01:00
/go/src/github.com/x/y/vendor/google.golang.org/protobuf/internal/impl/encode.go:79 +0xd9 fp=0xc004d51748 sp=0xc004d516f0 pc=0x7ff019
7430
2021-10-20T05:10:15.787+01:00
google.golang.org/protobuf/internal/impl.(*MessageInfo).sizePointer(0x0, {0x0}, {0x59})
7431
2021-10-20T05:10:15.787+01:00
/go/src/github.com/x/y/vendor/google.golang.org/protobuf/internal/impl/encode.go:56 +0x76 fp=0xc004d51780 sp=0xc004d51748 pc=0x7feef6
7432
2021-10-20T05:10:15.787+01:00
google.golang.org/protobuf/internal/impl.(*MessageInfo).size(0x1b70e28, {{}, {0x1bf65f8, 0xc007f21810}, 0xb8})
7433
2021-10-20T05:10:15.787+01:00
/go/src/github.com/x/y/vendor/google.golang.org/protobuf/internal/impl/encode.go:40 +0x52 fp=0xc004d517a8 sp=0xc004d51780 pc=0x7fee12
7434
2021-10-20T05:10:15.787+01:00
google.golang.org/protobuf/internal/impl.(*MessageInfo).size-fm({{}, {0x1bf65f8, 0xc007f21810}, 0x0})
7435
2021-10-20T05:10:15.787+01:00
/go/src/github.com/x/y/vendor/google.golang.org/protobuf/internal/impl/encode.go:33 +0x3b fp=0xc004d517d8 sp=0xc004d517a8 pc=0x8192db
7436
2021-10-20T05:10:15.787+01:00
google.golang.org/protobuf/proto.MarshalOptions.marshal({{}, 0x10, 0x0, 0x0}, {0x0, 0x203002, 0x2e}, {0x1bf65f8, 0xc007f21810})
7437
2021-10-20T05:10:15.787+01:00
/go/src/github.com/x/y/vendor/google.golang.org/protobuf/proto/encode.go:153 +0x148 fp=0xc004d51888 sp=0xc004d517d8 pc=0x7a5e08
7438
2021-10-20T05:10:15.787+01:00
google.golang.org/protobuf/proto.Marshal({0x1b99400, 0xc007f21810})
7439
2021-10-20T05:10:15.787+01:00
/go/src/github.com/x/y/vendor/google.golang.org/protobuf/proto/encode.go:79 +0x52 fp=0xc004d518d8 sp=0xc004d51888 pc=0x7a5912
7440
…
7443
2021-10-20T05:10:15.784+01:00
runtime: bad pointer in frame google.golang.org/protobuf/internal/impl.(*MessageInfo).sizePointerSlow at 0xc004d51570: 0x26
7444
2021-10-20T05:10:15.784+01:00
fatal error: invalid pointer found on stack
```

**What did you expect to see?**

No panic or at least a recoverable one.

**What did you see instead?**

An unrecoverable runtime error: https://github.com/golang/go/blob/d2ec73c1bfb556c5736f900a8e4a07e281450eb2/src/runtime/stack.go#L619

**Anything else we should know about your project / environment?**

**Comment by puellanivis** [comment]
This stack trace really doesn’t make sense, except in light of memory corruption. There are values that should be the same between frame N, and N+1, but they’re not.

**Comment by danielcondemarin** [comment]
> Without a reproduction case, I'm afraid there isn't much we can do.
> 
> The protobuf marshaler is heavily used in a number of different environments. While it certainly isn't impossible that it contains bugs, it is likely that the root cause lies elsewhere. This panic is reporting memory corruption, which can result in panics that occur far from the place where the corruption initially occurred. In other words, while the panic is occurring in `proto.Marshal`, that does not necessarily indicate that the source of the bug is in `proto.Marshal`.
> 
> If you can produce a reproduction case, we might be able to investigate further.

I understand, I'll keep trying to reproduce.
