### ISSUE TITLE
(*textWriter).writeQuotedString happens panic

### ISSUE THREAD

**Issue by Smicry** [golang/protobuf#1420]
hi, when I print string by xxx.String() function, it happens panic. 

version: 1.5.2

occured at this line: `switch c := s[i]; c {`
```
// writeQuotedString writes a quoted string in the protocol buffer text format.
func (w *textWriter) writeQuotedString(s string) {
	w.WriteByte('"')
	for i := 0; i < len(s); i++ {
		switch c := s[i]; c {
		case '\n':
			w.buf = append(w.buf, `\n`...)
		case '\r':
			w.buf = append(w.buf, `\r`...)
		case '\t':
			w.buf = append(w.buf, `\t`...)
		case '"':
			w.buf = append(w.buf, `\"`...)
		case '\\':
			w.buf = append(w.buf, `\\`...)
		default:
			if isPrint := c >= 0x20 && c < 0x7f; isPrint {
				w.buf = append(w.buf, c)
			} else {
				w.buf = append(w.buf, fmt.Sprintf(`\%03o`, c)...)
			}
		}
	}
	w.WriteByte('"')
}
```

panic message:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x695ba0]

goroutine 342537473 [running]:
github.com/golang/protobuf/proto.(*textWriter).writeQuotedString(0xc014ecb440, 0x0, 0x8)
	/root/go/pkg/mod/github.com/golang/protobuf@v1.5.2/proto/text_encode.go:410 +0xa0
github.com/golang/protobuf/proto.(*textWriter).writeSingularValue(0xc014ecb440, 0x28fdcc0, 0x0, 0x8, 0x36efea8, 0xc000d12740, 0xc00d169ec0, 0xc009619950)
	/root/go/pkg/mod/github.com/golang/protobuf@v1.5.2/proto/text_encode.go:369 +0x9af
github.com/golang/protobuf/proto.(*textWriter).writeMessage(0xc014ecb440, 0x36e6098, 0xc00d169ec0, 0x0, 0x0)
	/root/go/pkg/mod/github.com/golang/protobuf@v1.5.2/proto/text_encode.go:341 +0x1133
github.com/golang/protobuf/proto.(*textWriter).writeSingularValue(0xc014ecb440, 0x2fc3900, 0xc00d169ec0, 0x0, 0x36efea8, 0xc001153800, 0x2bf25e0, 0x7f5280c8af01)
	/root/go/pkg/mod/github.com/golang/protobuf@v1.5.2/proto/text_encode.go:390 +0x2a5
github.com/golang/protobuf/proto.(*textWriter).writeMessage(0xc014ecb440, 0x36e6098, 0xc00d169eb0, 0x0, 0x0)
	/root/go/pkg/mod/github.com/golang/protobuf@v1.5.2/proto/text_encode.go:341 +0x1133
github.com/golang/protobuf/proto.(*TextMarshaler).marshal(0x506d82c, 0x3680188, 0xc01398d3b0, 0xc012c8e000, 0x2df, 0x300, 0x0, 0x0)
	/root/go/pkg/mod/github.com/golang/protobuf@v1.5.2/proto/text_encode.go:86 +0x193
github.com/golang/protobuf/proto.(*TextMarshaler).Text(...)
	/root/go/pkg/mod/github.com/golang/protobuf@v1.5.2/proto/text_encode.go:44
github.com/golang/protobuf/proto.CompactTextString(...)
	/root/go/pkg/mod/github.com/golang/protobuf@v1.5.2/proto/text_encode.go:106
************************************************.String(...)
```

**Comment by puellanivis** [comment]
> `writeQuotedString(0xc014ecb440, 0x0, 0x8)`

This part of the stack trace is saying that it is trying to write a string that starts at address 0, and is 8 bytes long. This is definitely erroneous, and I’m having difficulty understanding how this could ever be possible. How are your protobuf messages being generated?

**Comment by Smicry** [comment]
> > `writeQuotedString(0xc014ecb440, 0x0, 0x8)`
> 
> This part of the stack trace is saying that it is trying to write a string that starts at address 0, and is 8 bytes long. This is definitely erroneous, and I’m having difficulty understanding how this could ever be possible. How are your protobuf messages being generated?

libprotoc 3.17.0
protoc-gen-go v1.25.0

**Comment by puellanivis** [comment]
Is this something that you can build a reliable reproduction for? Without more details, and a repro this is going to be impossible to pick apart, especially with all this memory weirdness going on.

**Comment by Smicry** [comment]
> Is this something that you can build a reliable reproduction for? Without more details, and a repro this is going to be impossible to pick apart, especially with all this memory weirdness going on.

ok, I will try it ! 
Thanks!

**Comment by yywing** [comment]
What is your go version？ 

Maybe https://github.com/golang/go/issues/67255
