### ISSUE TITLE
Enum String() resulting in panic

### ISSUE THREAD

**Issue by subuqq** [golang/protobuf#1426]
**What version of protobuf and what language are you using?**
Version: Proto3.
github.com/golang/protobuf v1.5.2/go.mod h1:XVQd3VNwM+JqD3oG2Ue2ip4fOMUkwXdXDdiuN0vRsmY=
Language: Go

**What operating system (Linux, Windows, ...) and version?** Windows10

**What runtime / compiler are you using (e.g., python version or gcc version)** 
see above
**What did you do?**
Create a simple Enum file
```
syntax = "proto3";

option go_package = "github.com/subuqq/Automata/common";

package common;

enum TestEnum {
  TestEnum_INVALID = 0;
  APPLE = 1;
  ORANGE = 2;
}

```

Generate Go classes
```

protoc -I . --go_out=./common --go_opt=module=github.com/subuqq/Automata/common --go-grpc_out=./common --go-grpc_opt=module=github.com/subuqq/Automata/common protos/test_enum.proto 
```

This generates a Go file with no initialization of enumTypes
```

func (x TestEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TestEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_test_enum_proto_enumTypes[0].Descriptor()
}
...
var file_protos_test_enum_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protos_test_enum_proto_goTypes = []interface{}{
	(TestEnum)(0), // 0: common.TestEnum
}
...
```

**What did you expect to see**
String should work
**What did you see instead?**
Panic from nil pointer reference above
```
anic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x78 pc=0x449ea2]

goroutine 1 [running]:
google.golang.org/protobuf/internal/impl.Export.EnumStringOf({}, {0x0, 0x0}, 0x1)
	C:/Users/subu/go/pkg/mod/google.golang.org/protobuf@v1.27.1/internal/impl/api_export.go:75 +0x22
github.com/subuqq/Automata/common.TestEnum.String(...)
	C:/Users/subu/go/src/github.com/subuqq/Automata/common/test_enum.pb.go:52
...
```
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**
Got bounced here from https://github.com/protocolbuffers/protobuf/issues/9663

**Comment by lfolger** [comment]
Could you clarify which version you are using?

In the "What version of protobuf and what language are you using?" section you state that you are using [protov1](https://pkg.go.dev/github.com/golang/protobuf). However the stacktrace suggests you are using [protov2](https://pkg.go.dev/google.golang.org/protobuf).

Could you add the code that led to this panic? I'm not sure I understand what exactly you were trying to do and where the panic could be comming from (since there are no pointers involved).

**Comment by aniruddha18ok** [comment]
Getting same issue : 
`panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x78 pc=0x118d4a2]

goroutine 1 [running]:
google.golang.org/protobuf/internal/impl.Export.EnumStringOf({}, {0x0, 0x0}, 0x0)
        /Users/okcreditmacbookpro/dev/go-workspace/pkg/mod/google.golang.org/protobuf@v1.27.1/internal/impl/api_export.go:75 +0x22
github.com/okcredit/subscription/service.Test.String(...)
        /Users/okcreditmacbookpro/Okcredit/subscription/service/subscription_service.pb.go:46
github.com/okcredit/subscription/service.init()
        /Users/okcreditmacbookpro/Okcredit/subscription/service/subscription_helper.go:10 +0xd0f
`

on subscription_helper.go at line number 10 
`var a = Test_TEST_VAL.String()`

version information:
`protoc-gen-go v1.27.1
protoc        v3.17.3`

**Comment by puellanivis** [comment]
```
github.com/okcredit/subscription/service.Test.String(...)
        /Users/okcreditmacbookpro/Okcredit/subscription/service/subscription_service.pb.go:46
github.com/okcredit/subscription/service.init()
        /Users/okcreditmacbookpro/Okcredit/subscription/service/subscription_helper.go:10 +0xd0f
```

So, here’s the fun thing about how Go orders `func init() { … }` functions: in order to ensure deterministic execution, they are executed from files by alphabetic name of the file, and within the file, from top to bottom. So, your `service.init()` function in `subscription_helper.go` is executing before the `init()` call in `subscription_service.pb.go`. Thus, the enum is not initialized yet.

It’s strongly recommend to isolate protobuf code into a separate page,

**Comment by aniruddha18ok** [comment]
Thank you @puellanivis for above informations, it solves my issue. Though there are couple of observations :

1. my `subscription_helper.go` doesn't have  any `init()` function. When I try changing file name to `x_subscription_helper.go` , it still didn't work. I believe it's because `service.init()` still has prior in execution order than `subscription_service.pb.go` ' s `init()` function. Same error even when I added `init()` in `subscription_helper.go` and initialized `var a = Test_TEST_VAL.String()` there.
2. Whithin same package, when I renamed to `x_subscription_helper.go` and put `var a = Test_TEST_VAL.String()` in `init()` it worked withoug any error
