### ISSUE TITLE
jsonpb: unable to unmarshal repeated enums

### ISSUE THREAD

**Issue by dsnet** [golang/protobuf#164]
Using:
* `protoc`: `v3.0.0-beta-2`
* `github.com/protobuf`: `dda510ac0fd43b39770f22ac6260eb91d377bce3`

Consider the following proto:
```proto
syntax = "proto3";

package google.security.safebrowsing.v4;

enum ThreatType {
  THREAT_TYPE_UNSPECIFIED = 0;
  MALWARE = 1;
  SOCIAL_ENGINEERING = 2;
  UNWANTED_SOFTWARE = 3;
  POTENTIALLY_HARMFUL_APPLICATION = 4;
}

message ThreatInfo {
  repeated ThreatType threat_types = 1;
}
```

Running a round-trip JSON marshal/unmarshal fails:
```go
func main() {
	msg := &ThreatInfo{ThreatTypes: []ThreatType{0, 1, 2, 3, 4}}

	// This marshals just fine, but use string names for enums
	var b bytes.Buffer
	var m jsonpb.Marshaler
	if err := m.Marshal(&b, msg); err != nil {
		panic(err)
	}

	fmt.Println(b.String())

	// This fails to unmarshal as it cannot handle strings for enums
	var msg2 ThreatInfo
	if err := jsonpb.Unmarshal(&b, &msg2); err != nil {
		panic(err)
	}
}
```

It outputs:
```
{"threatTypes":["THREAT_TYPE_UNSPECIFIED","MALWARE","SOCIAL_ENGINEERING","UNWANTED_SOFTWARE","POTENTIALLY_HARMFUL_APPLICATION"]}
panic: json: cannot unmarshal string into Go value of type main.ThreatType

goroutine 1 [running]:
panic(0x4e3ac0, 0xc8200184b0)
	/home/rawr/Projects/go/src/runtime/panic.go:500 +0x18a
main.main()
	/home/rawr/Projects/protofail/main.go:22 +0x291
exit status 2
```

@shahbag

**Comment by dinowernli** [comment]
FYI this is in-flight: https://github.com/golang/protobuf/pull/163

Should fix the problem.

**Comment by dsnet** [comment]
@dinowernli, awesome! Thanks for pointing that out.

**Comment by dsnet** [comment]
Thanks for fixing this!
