### ISSUE TITLE
google.golang.org/protobuf/types/known/structpb: TestToStruct fails at Go tip after the runtime map change in Go CL 627716

### ISSUE THREAD

**Issue by dmitshur** [golang/protobuf#1656]
The TestToStruct test in `google.golang.org/protobuf/types/known/structpb` package has started to fail at Go tip, as of [go.dev/cl/627716](https://go.dev/cl/627716) (CC @randall77):

```
=== RUN   TestToStruct
--- FAIL: TestToStruct (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x402751]

goroutine 18 [running]:
testing.tRunner.func1.2({0x72aa40, 0xa171b0})
	/home/swarming/.swarming/w/ir/x/w/goroot/src/testing/testing.go:1706 +0x21c
testing.tRunner.func1()
	/home/swarming/.swarming/w/ir/x/w/goroot/src/testing/testing.go:1709 +0x35e
panic({0x72aa40?, 0xa171b0?})
	/home/swarming/.swarming/w/ir/x/w/goroot/src/runtime/panic.go:787 +0x132
github.com/google/go-cmp/cmp/internal/value.isLess({0x712c60?, 0xc00011bcd0?, 0xc000137a00?}, {0x712c60?, 0xc00011bca0?, 0xc000126c18?})
	/home/swarming/.swarming/w/ir/x/w/gopath/pkg/mod/github.com/google/go-cmp@v0.5.5/cmp/internal/value/sort.go:59 +0xb1e
github.com/google/go-cmp/cmp/internal/value.SortKeys.func1(0xc00012cea0?, 0xc000110ed8?)
	/home/swarming/.swarming/w/ir/x/w/gopath/pkg/mod/github.com/google/go-cmp@v0.5.5/cmp/internal/value/sort.go:22 +0x4f
sort.insertionSort_func({0xc000110f80?, 0xc000202ea0?}, 0x14, 0x26)
	/home/swarming/.swarming/w/ir/x/w/goroot/src/sort/zsortfunc.go:12 +0xa7
sort.stable_func({0xc000110f80?, 0xc000202ea0?}, 0x26)
	/home/swarming/.swarming/w/ir/x/w/goroot/src/sort/zsortfunc.go:343 +0x75
sort.SliceStable({0x70d260?, 0xc000126c00?}, 0xc000110f80)
	/home/swarming/.swarming/w/ir/x/w/goroot/src/sort/slice.go:44 +0xb0
github.com/google/go-cmp/cmp/internal/value.SortKeys({0xc000137808, 0x26, 0x2a})
	/home/swarming/.swarming/w/ir/x/w/gopath/pkg/mod/github.com/google/go-cmp@v0.5.5/cmp/internal/value/sort.go:22 +0x9e
github.com/google/go-cmp/cmp.(*state).compareMap(0xc0001308c0, {0x7ff880, 0xc0001be930}, {0xc0001be930?, 0xc0001f6780?, 0x0?}, {0xc0001be930?, 0xc0001f7d70?, 0x0?})
	/home/swarming/.swarming/w/ir/x/w/gopath/pkg/mod/github.com/google/go-cmp@v0.5.5/cmp/compare.go:539 +0x3de
github.com/google/go-cmp/cmp.(*state).compareAny(0xc0001308c0, {0x7f8b70, 0xc0001f9200})
	/home/swarming/.swarming/w/ir/x/w/gopath/pkg/mod/github.com/google/go-cmp@v0.5.5/cmp/compare.go:290 +0xb29
github.com/google/go-cmp/cmp.(*state).compareInterface(0xc0001308c0, {0x7ff880?, 0x7240a0?}, {0x7240a0?, 0xc00011bb00?, 0x3?}, {0x7240a0?, 0xc00011bb10?, 0xc000202de0?})
	/home/swarming/.swarming/w/ir/x/w/gopath/pkg/mod/github.com/google/go-cmp@v0.5.5/cmp/compare.go:592 +0x305
github.com/google/go-cmp/cmp.(*state).compareAny(0xc0001308c0, {0x7f8b10, 0xc00013e960})
	/home/swarming/.swarming/w/ir/x/w/gopath/pkg/mod/github.com/google/go-cmp@v0.5.5/cmp/compare.go:294 +0xadd
github.com/google/go-cmp/cmp.(*state).compareMap(0xc0001308c0, {0x7ff880, 0x763ba0}, {0x763ba0?, 0xc0001f65d0?, 0x10002?}, {0x763ba0?, 0xc0001f7d10?, 0xc00016c0f0?})
	/home/swarming/.swarming/w/ir/x/w/gopath/pkg/mod/github.com/google/go-cmp@v0.5.5/cmp/compare.go:561 +0x566
github.com/google/go-cmp/cmp.(*state).compareAny(0xc0001308c0, {0x7f8ba0, 0xc00016e5a0})
	/home/swarming/.swarming/w/ir/x/w/gopath/pkg/mod/github.com/google/go-cmp@v0.5.5/cmp/compare.go:290 +0xb29
github.com/google/go-cmp/cmp.(*state).statelessCompare(0xc0001308c0, {0x7f8ba0?, 0xc00016e5a0?})
	/home/swarming/.swarming/w/ir/x/w/gopath/pkg/mod/github.com/google/go-cmp@v0.5.5/cmp/compare.go:229 +0x7a
github.com/google/go-cmp/cmp.(*state).callTRFunc(0xc0001308c0, {0x71fd40?, 0xc00011aff0?, 0x75f840?}, {0x75f840?, 0xc000129410?, 0x411254?}, {0x418c96?})
	/home/swarming/.swarming/w/ir/x/w/gopath/pkg/mod/github.com/google/go-cmp@v0.5.5/cmp/compare.go:334 +0x2ba
github.com/google/go-cmp/cmp.(*transformer).apply(0xc0001f80c0, 0xc0001308c0, {0x75f840?, 0xc000129410?, 0xc000111a78?}, {0x75f840?, 0xc0001f64e0?, 0x7ff880?})
	/home/swarming/.swarming/w/ir/x/w/gopath/pkg/mod/github.com/google/go-cmp@v0.5.5/cmp/options.go:320 +0x139
github.com/google/go-cmp/cmp.(*state).tryOptions(0xc0001308c0, {0x7ff880?, 0x75f840?}, {0x75f840?, 0xc000129410?, 0x7e7aac21e668?}, {0x75f840?, 0xc0001f64e0?, 0xa28260?})
	/home/swarming/.swarming/w/ir/x/w/gopath/pkg/mod/github.com/google/go-cmp@v0.5.5/cmp/compare.go:303 +0xf3
github.com/google/go-cmp/cmp.(*state).compareAny(0xc0001308c0, {0x7f8bd0, 0xc0001f8100})
	/home/swarming/.swarming/w/ir/x/w/gopath/pkg/mod/github.com/google/go-cmp@v0.5.5/cmp/compare.go:258 +0x4bf
github.com/google/go-cmp/cmp.Diff({0x75f840, 0xc000129410}, {0x75f840, 0xc0001f64e0}, {0xc00011b020?, 0xa08c80?, 0xc00005a600?})
	/home/swarming/.swarming/w/ir/x/w/gopath/pkg/mod/github.com/google/go-cmp@v0.5.5/cmp/compare.go:119 +0x75
google.golang.org/protobuf/types/known/structpb_test.TestToStruct(0xc000102700)
	/home/swarming/.swarming/w/ir/x/w/targetrepo495428555/types/known/structpb/struct_test.go:101 +0x1c25
testing.tRunner(0xc000102700, 0x796c60)
	/home/swarming/.swarming/w/ir/x/w/goroot/src/testing/testing.go:1764 +0xf4
created by testing.(*T).Run in goroutine 1
	/home/swarming/.swarming/w/ir/x/w/goroot/src/testing/testing.go:1823 +0x409
```

See [LUCI build 8730991062707988305](https://ci.chromium.org/ui/p/golang/builders/ci/z_protobuf-gotip-linux-amd64/b8730991062707988305/test-results?q=ExactID%3Agoogle.golang.org%2Fprotobuf%2Ftypes%2Fknown%2Fstructpb.TestToStruct+VHash%3A8391ab9c21a21367).

CC @chressie.

**Comment by dmitshur** [comment]
This failure no longer happens at Go tip as of https://go.dev/cl/630279.
