### ISSUE TITLE
[protoreflect] Message.WhichOneof for generated message type panics when given synthetic oneof

### ISSUE THREAD

**Issue by jhump** [golang/protobuf#1659]
**What version of protobuf and what language are you using?**
v1.36.0

**What did you do?**
Here's a reproducer test case.
https://github.com/protocolbuffers/protobuf-go/compare/master...jhump:protobuf-go:jh/panic-repro
The panic happens in the call to `msg.WhichOneof` (line 20).

**What did you expect to see?**
In prior versions, at least as recently as 1.34.0, this worked as expected. It would return nil if the underlying proto3 optional field was present and otherwise it would return its field descriptor.

**What did you see instead?**
```
panic: invalid oneof descriptor goproto.proto.test3.TestAllTypes._optional_int32 for message goproto.proto.test3.TestAllTypes [recovered]
	panic: invalid oneof descriptor goproto.proto.test3.TestAllTypes._optional_int32 for message goproto.proto.test3.TestAllTypes

goroutine 21 [running]:
testing.tRunner.func1.2({0x10096da60, 0x1400008f2a0})
	/Users/jhumphries/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.4.darwin-arm64/src/testing/testing.go:1632 +0x1bc
testing.tRunner.func1()
	/Users/jhumphries/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.4.darwin-arm64/src/testing/testing.go:1635 +0x334
panic({0x10096da60?, 0x1400008f2a0?})
	/Users/jhumphries/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.4.darwin-arm64/src/runtime/panic.go:785 +0x124
google.golang.org/protobuf/internal/impl.(*messageState).WhichOneof(0x140000fc908, {0x1009cb318, 0x1400014a098})
	/Users/jhumphries/src/protobuf-go/internal/impl/message_reflect_gen.go:126 +0x194
google.golang.org/protobuf/reflect/protoreflect_test.TestSyntheticOneof(0x140000ac9c0)
	/Users/jhumphries/src/protobuf-go/reflect/protoreflect/oneof_test.go:20 +0x108
testing.tRunner(0x140000ac9c0, 0x1009c5868)
	/Users/jhumphries/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.4.darwin-arm64/src/testing/testing.go:1690 +0xe4
created by testing.(*T).Run in goroutine 1
	/Users/jhumphries/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.4.darwin-arm64/src/testing/testing.go:1743 +0x314
```

**Anything else we should know about your project / environment?**
Occurs on both OS X and Linux.

The following patch fixes the issue:
```diff
diff --git a/internal/impl/message_reflect_gen.go b/internal/impl/message_reflect_gen.go
index 99dc23c6..f12524be 100644
--- a/internal/impl/message_reflect_gen.go
+++ b/internal/impl/message_reflect_gen.go
@@ -123,6 +123,17 @@ func (m *messageState) WhichOneof(od protoreflect.OneofDescriptor) protoreflect.
        if oi := mi.oneofs[od.Name()]; oi != nil && oi.oneofDesc == od {
                return od.Fields().ByNumber(oi.which(m.pointer()))
        }
+       if od.Parent() == m.Descriptor() && od.IsSynthetic() {
+               // Synthetic oneofs are absent from mi.oneofs, so fallback to slow way.
+               fields := od.Fields()
+               for i, length := 0, fields.Len(); i < length; i++ {
+                       fd := fields.Get(i)
+                       if m.Has(fd) {
+                               return fd
+                       }
+               }
+               return nil
+       }
        panic("invalid oneof descriptor " + string(od.FullName()) + " for message " + string(m.Descriptor().FullName()))
 }
 func (m *messageState) GetUnknown() protoreflect.RawFields {
```

However, the file in question (`internal/impl/message_reflect_gen.go`) is generated. So a real fix will have to be made in the code generator or perhaps to reverse whatever change caused synthetic oneofs to no longer appear in `mi.oneofs`.

**Comment by bwester** [comment]
I also just encountered this panic in v1.36.0 through a different route. Attempting to encode a message using `github.com/golang/protobuf/jsonpb` when that message's descriptor contains a synthetic oneof will trigger the panic at `message_reflect_gen.go:126`.  I bisected `google.golang.org/protobuf` to find that this behavior was introduced with commit [bdcc7adc94f2](https://github.com/protocolbuffers/protobuf-go/commit/bdcc7adc94f2005be83ac21fda8c5eb4f5890400).

I am aware `jsonpb` has been deprecated a long time. It is unfortunately still in use in some code I work with. Also, I was thankfully unable to get `protojson` to show the same error.

**Comment by rbroggi** [comment]
version `v1.35.2` still did not have this issue. Breaking change was introduced in `v1.36.0`

**Comment by puellanivis** [comment]
Current behavior is documented to be correct:
> 				// Synthetic oneofs are used to represent optional fields in
>				// proto3. While they show up in protoreflect, WhichOneof does
>				// not work on these (only on non-synthetic, explicit oneofs).

That is: calling `WhichOneOf` for an optional field _should_ not work exactly like call calling `WhichOneOf` for a non-optional simple scalar outside of a `oneof`.

**Comment by rbroggi** [comment]
Regardless of the documentation correctness, this seems to be a breaking change - I've experienced many services breaking due to this and it breaks in a vey bad way since it's something that is frequently not tested - production servers panicking. Maybe it has the extremes for a security vulnerability?

**Comment by puellanivis** [comment]
I believe this is not the Security exception to go1compat, but Bugs according to the go1compat rules. This behavior never should have worked, because optional fields were never actually oneofs. Therefore, that this worked before was out of specification.

**Comment by rbroggi** [comment]
I am quite unknowledgeable on the rules, it still feel very that is a drastic behavioral change, if this wasn't supposed to work before I would have expected compilation issues, right now we have a situation where attackers can crash a server by just tuning some query parameters which is a great recipe for denial of service attacks. Maybe it shouldn't have been there from the beginning but it is already out and there are people running servers out there leveraging this behavior. If we want to pursue this correction my take is that it should come with a more diligent governance starting from the compiler, going through (if possible) deprecation warnings and only at the very end panicking.

**Comment by rbroggi** [comment]
In my case I am experiencing that when using in conjunction with grpc-gateway:

```proto
rpc Echo(MessageRequest) returns (MessageResponse) {
  option (google.api.http) = {
    get: "/v1/example/resource"
  };
}

message MessageRequest {
  int32 query_filter = 1;
  optional string optional_query_filter = 2;

}
```

**Comment by jhump** [comment]
Possibly relevant observation: `*dynamicpb.Message` works just fine when its `WhichOneof` method is called with a synthetic oneof.

**Comment by puellanivis** [comment]
Relevant `grpc-gateway` PR https://github.com/grpc-ecosystem/grpc-gateway/pull/5072

**Comment by neild** [comment]
If this changed, we should probably restore the original behavior regardless of what the documentation says.

**Comment by stapelberg** [comment]
Sorry for the breakage, folks. Maybe I misunderstood something in how this behavior is meant to work. I’ll look into it on Monday when I’m in the office.

**Comment by stapelberg** [comment]
OK, I have had a chance to look into this issue some more.

As I suspected, I had not correctly understood the situation when I made this change. I’m sorry for the extra work this caused everyone.

By now, we have made two changes:

1. We released version v1.36.1 which [contains a fix](https://github.com/protocolbuffers/protobuf-go/commit/575aebf635cba30f5545193609d80c647dce68ea) that restores the old behavior for the Open Struct API. If you ran into this issue when updating Go Protobuf and you are not yet [using the Opaque API](https://go.dev/blog/protobuf-opaque), upgrading to v1.36.1 should be sufficient to pick up the fix.
2. I submitted [another fix](https://github.com/protocolbuffers/protobuf-go/commit/8878926ea7902e940d3a9a8b1d194a4140348ca8) that unifies behavior of the Opaque API with the other API levels when using optional fields in proto3 files. This change is not included in the v1.36.1 release yet to not cause any unnecessary risk over the holiday period. Please upgrade to version `v1.36.2-0.20241223133329-8878926ea790` or newer to pick up this fix.

We will release v1.36.2 in January and will leave this issue open until then for visibility. Happy holidays everyone!

**Comment by stapelberg** [comment]
Happy new year!

v1.36.2 has just now been released: https://github.com/protocolbuffers/protobuf-go/releases/tag/v1.36.2
