### ISSUE TITLE
jsonpb: Unmarshalling Struct panics

### ISSUE THREAD

**Issue by vinceferro** [golang/protobuf#568]
Hey, having troubles with unmarshaling with a struct.

`reflect.Set: value of type map[string]*structpb.Value is not assignable to type map[string]*structpb.Value`

This is the protobuf definition:

```
syntax = "proto3";

package sessions;

import "google/protobuf/struct.proto";

message SessionId {
  string session_id = 1;
}

message Session {
  SessionId session_id = 1;
  google.protobuf.Struct session_data = 2;
}
```

My go version is 1.10.

Any insights?

Thanks

**Comment by dsnet** [comment]
Hi, this is report is too vague for us to assist in a meaningful way.

Please post the following:
* Full stack trace of the panic
* The generated .pb.go source
* The version of `protoc` being used.
* The version of `protoc-gen-go` being used.

If proprietary code is involved, please strip it down to a minimal reproduction. Thank you.

**Comment by vinceferro** [comment]
Sure, so:

- protoc version: v3.5.1
- protoc-gen-go: I guess v1.0.0
- Stack trace below
- .pb.go below

Thank you!

Stack trace:

```
--- FAIL: Test_server_WriteSession (0.00s)
panic: reflect.Set: value of type map[string]*structpb.Value is not assignable to type map[string]*structpb.Value [recovered]
	panic: reflect.Set: value of type map[string]*structpb.Value is not assignable to type map[string]*structpb.Value

goroutine 20 [running]:
testing.tRunner.func1(0xc4201b60f0)
	/usr/local/opt/go/libexec/src/testing/testing.go:742 +0x29d
panic(0x148c920, 0xc4200b7540)
	/usr/local/opt/go/libexec/src/runtime/panic.go:505 +0x229
reflect.Value.assignTo(0x14ba400, 0xc4201b43f0, 0x15, 0x15695a8, 0xb, 0x14ba520, 0x0, 0x100924d, 0x14ba400, 0xc4201b43f0)
	/usr/local/opt/go/libexec/src/reflect/value.go:2235 +0x427
reflect.Value.Set(0x14ba520, 0xc4200d00a0, 0x195, 0x14ba400, 0xc4201b43f0, 0x15)
	/usr/local/opt/go/libexec/src/reflect/value.go:1373 +0xa4
github.com/golang/protobuf/jsonpb.(*Unmarshaler).unmarshalValue(0xc42019c5a0, 0x14d2e00, 0xc4200d00a0, 0x199, 0xc4200be960, 0x10, 0x10, 0xc42012e8c0, 0x0, 0x0)
	/Users/vincenzo/go-workspace/src/github.com/golang/protobuf/jsonpb/jsonpb.go:791 +0x2190
github.com/golang/protobuf/jsonpb.(*Unmarshaler).unmarshalValue(0xc42019c5a0, 0x14f54a0, 0xc4200b7488, 0x196, 0xc4200be960, 0x10, 0x10, 0xc42012e8c0, 0x14c0105, 0x57)
	/Users/vincenzo/go-workspace/src/github.com/golang/protobuf/jsonpb/jsonpb.go:682 +0x292
github.com/golang/protobuf/jsonpb.(*Unmarshaler).unmarshalValue(0xc42019c5a0, 0x14e30a0, 0xc4200b7480, 0x199, 0xc4200ce0f0, 0x45, 0x50, 0x0, 0x15375e0, 0xc420077f01)
	/Users/vincenzo/go-workspace/src/github.com/golang/protobuf/jsonpb/jsonpb.go:900 +0x7bf
github.com/golang/protobuf/jsonpb.(*Unmarshaler).UnmarshalNext(0xc42019c5a0, 0xc4201d6000, 0x15c7b20, 0xc4200b7480, 0x1d12d01, 0xc42019c5c0)
	/Users/vincenzo/go-workspace/src/github.com/golang/protobuf/jsonpb/jsonpb.go:635 +0x139
github.com/golang/protobuf/jsonpb.(*Unmarshaler).Unmarshal(0xc42019c5a0, 0x15c3aa0, 0xc42019c5c0, 0x15c7b20, 0xc4200b7480, 0x14e30a0, 0xc4200be801)
	/Users/vincenzo/go-workspace/src/github.com/golang/protobuf/jsonpb/jsonpb.go:643 +0x7c
github.com/golang/protobuf/jsonpb.UnmarshalString(0x1580379, 0x45, 0x15c7b20, 0xc4200b7480, 0x15bfb60, 0x6fc23ac00)
	/Users/vincenzo/go-workspace/src/github.com/golang/protobuf/jsonpb/jsonpb.go:664 +0xae
github.com/italistdev/grpc-sessions-service.Test_server_WriteSession(0xc4201b60f0)
	/Users/vincenzo/go-workspace/src/github.com/italistdev/grpc-sessions-service/server_test.go:54 +0xf6
testing.tRunner(0xc4201b60f0, 0x1587370)
	/usr/local/opt/go/libexec/src/testing/testing.go:777 +0xd0
created by testing.(*T).Run
	/usr/local/opt/go/libexec/src/testing/testing.go:824 +0x2e0
FAIL	github.com/italistdev/grpc-sessions-service	0.029s
Error: Tests failed.
```

file .pb.go
```
// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sessions.proto

/*
Package sessions is a generated protocol buffer package.

It is generated from these files:
	sessions.proto

It has these top-level messages:
	SessionId
	Session
	StatusResponse
	ValidationResponse
*/
package sessions

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/empty"
import google_protobuf1 "github.com/golang/protobuf/ptypes/struct"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StatusResponse_Status int32

const (
	StatusResponse_FAILED  StatusResponse_Status = 0
	StatusResponse_SUCCESS StatusResponse_Status = 1
)

var StatusResponse_Status_name = map[int32]string{
	0: "FAILED",
	1: "SUCCESS",
}
var StatusResponse_Status_value = map[string]int32{
	"FAILED":  0,
	"SUCCESS": 1,
}

func (x StatusResponse_Status) String() string {
	return proto.EnumName(StatusResponse_Status_name, int32(x))
}
func (StatusResponse_Status) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 0} }

type SessionId struct {
	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId" json:"session_id,omitempty"`
}

func (m *SessionId) Reset()                    { *m = SessionId{} }
func (m *SessionId) String() string            { return proto.CompactTextString(m) }
func (*SessionId) ProtoMessage()               {}
func (*SessionId) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SessionId) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

type Session struct {
	SessionId   *SessionId               `protobuf:"bytes,1,opt,name=session_id,json=sessionId" json:"session_id,omitempty"`
	SessionData *google_protobuf1.Struct `protobuf:"bytes,2,opt,name=session_data,json=sessionData" json:"session_data,omitempty"`
}

func (m *Session) Reset()                    { *m = Session{} }
func (m *Session) String() string            { return proto.CompactTextString(m) }
func (*Session) ProtoMessage()               {}
func (*Session) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Session) GetSessionId() *SessionId {
	if m != nil {
		return m.SessionId
	}
	return nil
}

func (m *Session) GetSessionData() *google_protobuf1.Struct {
	if m != nil {
		return m.SessionData
	}
	return nil
}

type StatusResponse struct {
	Status StatusResponse_Status `protobuf:"varint,1,opt,name=status,enum=sessions.StatusResponse_Status" json:"status,omitempty"`
}

func (m *StatusResponse) Reset()                    { *m = StatusResponse{} }
func (m *StatusResponse) String() string            { return proto.CompactTextString(m) }
func (*StatusResponse) ProtoMessage()               {}
func (*StatusResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *StatusResponse) GetStatus() StatusResponse_Status {
	if m != nil {
		return m.Status
	}
	return StatusResponse_FAILED
}

type ValidationResponse struct {
	IsValid bool `protobuf:"varint,1,opt,name=is_valid,json=isValid" json:"is_valid,omitempty"`
}

func (m *ValidationResponse) Reset()                    { *m = ValidationResponse{} }
func (m *ValidationResponse) String() string            { return proto.CompactTextString(m) }
func (*ValidationResponse) ProtoMessage()               {}
func (*ValidationResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ValidationResponse) GetIsValid() bool {
	if m != nil {
		return m.IsValid
	}
	return false
}

func init() {
	proto.RegisterType((*SessionId)(nil), "sessions.SessionId")
	proto.RegisterType((*Session)(nil), "sessions.Session")
	proto.RegisterType((*StatusResponse)(nil), "sessions.StatusResponse")
	proto.RegisterType((*ValidationResponse)(nil), "sessions.ValidationResponse")
	proto.RegisterEnum("sessions.StatusResponse_Status", StatusResponse_Status_name, StatusResponse_Status_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Sessions service

type SessionsClient interface {
	ReadSession(ctx context.Context, in *SessionId, opts ...grpc.CallOption) (*Session, error)
	CreateSession(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*SessionId, error)
	WriteSession(ctx context.Context, in *Session, opts ...grpc.CallOption) (*StatusResponse, error)
	DestroySession(ctx context.Context, in *SessionId, opts ...grpc.CallOption) (*StatusResponse, error)
	ValidateSession(ctx context.Context, in *SessionId, opts ...grpc.CallOption) (*ValidationResponse, error)
}

type sessionsClient struct {
	cc *grpc.ClientConn
}

func NewSessionsClient(cc *grpc.ClientConn) SessionsClient {
	return &sessionsClient{cc}
}

func (c *sessionsClient) ReadSession(ctx context.Context, in *SessionId, opts ...grpc.CallOption) (*Session, error) {
	out := new(Session)
	err := grpc.Invoke(ctx, "/sessions.Sessions/ReadSession", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsClient) CreateSession(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*SessionId, error) {
	out := new(SessionId)
	err := grpc.Invoke(ctx, "/sessions.Sessions/CreateSession", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsClient) WriteSession(ctx context.Context, in *Session, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := grpc.Invoke(ctx, "/sessions.Sessions/WriteSession", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsClient) DestroySession(ctx context.Context, in *SessionId, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := grpc.Invoke(ctx, "/sessions.Sessions/DestroySession", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsClient) ValidateSession(ctx context.Context, in *SessionId, opts ...grpc.CallOption) (*ValidationResponse, error) {
	out := new(ValidationResponse)
	err := grpc.Invoke(ctx, "/sessions.Sessions/ValidateSession", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Sessions service

type SessionsServer interface {
	ReadSession(context.Context, *SessionId) (*Session, error)
	CreateSession(context.Context, *google_protobuf.Empty) (*SessionId, error)
	WriteSession(context.Context, *Session) (*StatusResponse, error)
	DestroySession(context.Context, *SessionId) (*StatusResponse, error)
	ValidateSession(context.Context, *SessionId) (*ValidationResponse, error)
}

func RegisterSessionsServer(s *grpc.Server, srv SessionsServer) {
	s.RegisterService(&_Sessions_serviceDesc, srv)
}

func _Sessions_ReadSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServer).ReadSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sessions.Sessions/ReadSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServer).ReadSession(ctx, req.(*SessionId))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sessions_CreateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServer).CreateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sessions.Sessions/CreateSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServer).CreateSession(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sessions_WriteSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Session)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServer).WriteSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sessions.Sessions/WriteSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServer).WriteSession(ctx, req.(*Session))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sessions_DestroySession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServer).DestroySession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sessions.Sessions/DestroySession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServer).DestroySession(ctx, req.(*SessionId))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sessions_ValidateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServer).ValidateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sessions.Sessions/ValidateSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServer).ValidateSession(ctx, req.(*SessionId))
	}
	return interceptor(ctx, in, info, handler)
}

var _Sessions_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sessions.Sessions",
	HandlerType: (*SessionsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReadSession",
			Handler:    _Sessions_ReadSession_Handler,
		},
		{
			MethodName: "CreateSession",
			Handler:    _Sessions_CreateSession_Handler,
		},
		{
			MethodName: "WriteSession",
			Handler:    _Sessions_WriteSession_Handler,
		},
		{
			MethodName: "DestroySession",
			Handler:    _Sessions_DestroySession_Handler,
		},
		{
			MethodName: "ValidateSession",
			Handler:    _Sessions_ValidateSession_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sessions.proto",
}

func init() { proto.RegisterFile("sessions.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 351 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x51, 0xcd, 0x4e, 0xf2, 0x40,
	0x14, 0x2d, 0x2c, 0x4a, 0xb9, 0xe5, 0xeb, 0x87, 0x63, 0xa2, 0x58, 0x31, 0xea, 0xac, 0x8c, 0x8b,
	0x92, 0xd4, 0x05, 0x89, 0x89, 0x26, 0x84, 0x9f, 0x84, 0xc4, 0x55, 0x1b, 0x75, 0x49, 0x06, 0x3b,
	0x92, 0x49, 0x90, 0x21, 0xbd, 0x83, 0x09, 0x0f, 0xe9, 0x3b, 0x19, 0xa6, 0x1d, 0x40, 0x8b, 0x5d,
	0xf6, 0xdc, 0xf3, 0x37, 0xa7, 0xe0, 0x21, 0x47, 0x14, 0x72, 0x81, 0xc1, 0x32, 0x95, 0x4a, 0x12,
	0xc7, 0x7c, 0xfb, 0xe7, 0x33, 0x29, 0x67, 0x73, 0xde, 0xd1, 0xf8, 0x74, 0xf5, 0xde, 0xe1, 0x1f,
	0x4b, 0xb5, 0xce, 0x68, 0x7e, 0xfb, 0xf7, 0x11, 0x55, 0xba, 0x7a, 0x53, 0xd9, 0x95, 0xde, 0x42,
	0x3d, 0xce, 0x6c, 0xc6, 0x09, 0xb9, 0x00, 0xc8, 0x3d, 0x27, 0x22, 0x69, 0x55, 0xae, 0x2a, 0x37,
	0xf5, 0xa8, 0x8e, 0xe6, 0x4c, 0xd7, 0x50, 0xcb, 0xb9, 0x24, 0x2c, 0x30, 0xdd, 0xf0, 0x38, 0xd8,
	0x16, 0xdc, 0x5a, 0xee, 0xc9, 0xc9, 0x3d, 0x34, 0x8c, 0x26, 0x61, 0x8a, 0xb5, 0xaa, 0x5a, 0x75,
	0x1a, 0x64, 0xfd, 0x02, 0xd3, 0x2f, 0x88, 0x75, 0xbf, 0xc8, 0xcd, 0xc9, 0x03, 0xa6, 0x18, 0x9d,
	0x83, 0x17, 0x2b, 0xa6, 0x56, 0x18, 0x71, 0x5c, 0xca, 0x05, 0x72, 0xd2, 0x05, 0x1b, 0x35, 0xa2,
	0xd3, 0xbd, 0xf0, 0x72, 0x2f, 0xfd, 0x07, 0xd3, 0x7c, 0xe6, 0x74, 0x7a, 0x0d, 0x76, 0x86, 0x10,
	0x00, 0x7b, 0xd4, 0x1b, 0x3f, 0x0d, 0x07, 0x4d, 0x8b, 0xb8, 0x50, 0x8b, 0x9f, 0xfb, 0xfd, 0x61,
	0x1c, 0x37, 0x2b, 0xb4, 0x03, 0xe4, 0x85, 0xcd, 0x45, 0xc2, 0x94, 0x90, 0x8b, 0x6d, 0xe2, 0x19,
	0x38, 0x02, 0x27, 0x9f, 0x9b, 0x83, 0xce, 0x74, 0xa2, 0x9a, 0x40, 0xcd, 0x0b, 0xbf, 0xaa, 0xe0,
	0xe4, 0x6f, 0x46, 0xd2, 0x05, 0x37, 0xe2, 0x2c, 0x31, 0x53, 0x1d, 0x9a, 0xc5, 0x3f, 0x2a, 0x80,
	0xd4, 0x22, 0x8f, 0xf0, 0xaf, 0x9f, 0x72, 0xa6, 0xb8, 0x91, 0x9e, 0x14, 0xb6, 0x19, 0x6e, 0x7e,
	0xac, 0x7f, 0xc8, 0x92, 0x5a, 0xe4, 0x01, 0x1a, 0xaf, 0xa9, 0xd8, 0xc9, 0x8b, 0x21, 0x7e, 0xeb,
	0xaf, 0x95, 0xa8, 0x45, 0x7a, 0xe0, 0x0d, 0x38, 0xaa, 0x54, 0xae, 0x4b, 0xab, 0x97, 0x59, 0x8c,
	0xe0, 0x7f, 0x3e, 0x1c, 0x2f, 0xf5, 0x68, 0xef, 0xc0, 0xe2, 0xd0, 0xd4, 0x9a, 0xda, 0xfa, 0xc1,
	0x77, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xdc, 0x45, 0x84, 0x91, 0xf3, 0x02, 0x00, 0x00,
}
```

**Comment by dsnet** [comment]
Is vendoring involved? This sounds like the package for `github.com/golang/protobuf/ptypes/struct` is different from the perspective of your `.pb.go` file and the `jsonpb` package.

**Comment by vinceferro** [comment]
Ha! Probably yes, I use `dep` to install and manage the dependencies. I've probably generated the .pb.go file before start using it. Let me check ;)

**Comment by vinceferro** [comment]
@dsnet Ok, that was it. I've removed vendor stuff and it worked!
I'm wondering what's the best way to handle it, do you have any suggestions?

**Comment by dsnet** [comment]
Great to hear. The best way is to stay on top of new developments with versioned go: https://blog.golang.org/versioning-proposal

**Comment by vinceferro** [comment]
Cool, thx @dsnet
