### ISSUE TITLE
jsonpb: test failed with appengine build tags

### ISSUE THREAD

**Issue by s-hashimoto00** [golang/protobuf#670]
test failed with appengine build tags.

go version:
```
$ go version
go version go1.10.3 linux/amd64
```

without build tags:
```
$ go test ./jsonpb/
ok      github.com/golang/protobuf/jsonpb       0.007s
```

with appengine build tags:
```
$ go test -tags=appengine ./jsonpb/
--- FAIL: TestMarshalAnyJSONPBMarshaler (0.00s)
panic: reflect.Value.Interface: cannot return value obtained from unexported field or method [recovered]
        panic: reflect.Value.Interface: cannot return value obtained from unexported field or method

goroutine 22 [running]:
testing.tRunner.func1(0xc4200ba4b0)
        /usr/local/go/src/testing/testing.go:742 +0x29d
panic(0x5da9a0, 0x663b20)
        /usr/local/go/src/runtime/panic.go:502 +0x229
reflect.valueInterface(0x5d1ce0, 0xc42007f800, 0x36, 0x1, 0xc420044c80, 0x4a128a)
        /usr/local/go/src/reflect/value.go:959 +0x1c1
reflect.Value.Interface(0x5d1ce0, 0xc42007f800, 0x36, 0xc42007f800, 0x1b8)
        /usr/local/go/src/reflect/value.go:948 +0x44
github.com/golang/protobuf/proto.pointer.toString(0x5d1ce0, 0xc42007f800, 0x36, 0x1b8)
        /root/gopath/src/github.com/golang/protobuf/proto/pointer_reflect.go:244 +0x3f
github.com/golang/protobuf/proto.sizeStringValueNoZero(0x5d1ce0, 0xc42007f800, 0x36, 0x1, 0x1)
        /root/gopath/src/github.com/golang/protobuf/proto/table_marshal.go:1229 +0x43
github.com/golang/protobuf/proto.(*marshalInfo).size(0xc420123340, 0x604a80, 0xc42007f800, 0x16, 0x40e18d)
        /root/gopath/src/github.com/golang/protobuf/proto/table_marshal.go:182 +0x12e
github.com/golang/protobuf/proto.(*InternalMessageInfo).Size(0xc42002ae40, 0x665140, 0xc42007f800, 0x0)
        /root/gopath/src/github.com/golang/protobuf/proto/table_marshal.go:124 +0xdd
github.com/golang/protobuf/proto.Marshal(0x665140, 0xc42007f800, 0x0, 0xf, 0x769d2b, 0x24, 0x2d2)
        /root/gopath/src/github.com/golang/protobuf/proto/table_marshal.go:2716 +0xf2
github.com/golang/protobuf/ptypes.MarshalAny(0x665140, 0xc42007f800, 0x2d2, 0x4d0d70, 0xc42007f701)
        /root/gopath/src/github.com/golang/protobuf/ptypes/any.go:66 +0x3c
github.com/golang/protobuf/jsonpb.TestMarshalAnyJSONPBMarshaler(0xc4200ba4b0)
        /root/gopath/src/github.com/golang/protobuf/jsonpb/jsonpb_test.go:587 +0x85
testing.tRunner(0xc4200ba4b0, 0x64a1d8)
        /usr/local/go/src/testing/testing.go:777 +0xd0
created by testing.(*T).Run
        /usr/local/go/src/testing/testing.go:824 +0x2e0
FAIL    github.com/golang/protobuf/jsonpb       0.007s
```

**Comment by dsnet** [comment]
Thank you for the report. I am able to reproduce.
